export const LANGUAGES = [
    { code: "af", name: "Afrikaans" },
    { code: "ar", name: "Arabic" },
    { code: "bg", name: "Bulgarian" },
    { code: "bn", name: "Bengali" },
    { code: "cs", name: "Czech" },
    { code: "da", name: "Danish" },
    { code: "de", name: "German" },
    { code: "el", name: "Greek" },
    { code: "en", name: "English" },
    { code: "es", name: "Spanish" },
    { code: "et", name: "Estonian" },
    { code: "fa", name: "Persian" },
    { code: "fi", name: "Finnish" },
    { code: "fr", name: "French" },
    { code: "gu", name: "Gujarati" },
    { code: "he", name: "Hebrew" },
    { code: "hi", name: "Hindi" },
    { code: "hr", name: "Croatian" },
    { code: "hu", name: "Hungarian" },
    { code: "id", name: "Indonesian" },
    { code: "it", name: "Italian" },
    { code: "ja", name: "Japanese" },
    { code: "kn", name: "Kannada" },
    { code: "ko", name: "Korean" },
    { code: "lt", name: "Lithuanian" },
    { code: "lv", name: "Latvian" },
    { code: "ml", name: "Malayalam" },
    { code: "mr", name: "Marathi" },
    { code: "ms", name: "Malay" },
    { code: "nl", name: "Dutch" },
    { code: "no", name: "Norwegian" },
    { code: "pa", name: "Punjabi" },
    { code: "pl", name: "Polish" },
    { code: "pt", name: "Portuguese" },
    { code: "ro", name: "Romanian" },
    { code: "ru", name: "Russian" },
    { code: "sk", name: "Slovak" },
    { code: "sl", name: "Slovenian" },
    { code: "so", name: "Somali" },
    { code: "sq", name: "Albanian" },
    { code: "sv", name: "Swedish" },
    { code: "sw", name: "Swahili" },
    { code: "ta", name: "Tamil" },
    { code: "te", name: "Telugu" },
    { code: "th", name: "Thai" },
    { code: "tl", name: "Filipino" },
    { code: "tr", name: "Turkish" },
    { code: "uk", name: "Ukrainian" },
    { code: "ur", name: "Urdu" },
    { code: "vi", name: "Vietnamese" },
    { code: "zh", name: "Chinese" },
];

export const LANGUAGE_TO_FLAG_CODE: Record<string, string> = {
    af: 'ZA', ar: 'SA', bg: 'BG', bn: 'BD', cs: 'CZ', da: 'DK',
    de: 'DE', el: 'GR', en: 'GB', es: 'ES', et: 'EE', fa: 'IR',
    fi: 'FI', fr: 'FR', gu: 'IN', he: 'IL', hi: 'IN', hr: 'HR',
    hu: 'HU', id: 'ID', it: 'IT', ja: 'JP', kn: 'IN', ko: 'KR',
    lt: 'LT', lv: 'LV', ml: 'IN', mr: 'IN', ms: 'MY', nl: 'NL',
    no: 'NO', pa: 'IN', pl: 'PL', pt: 'PT', ro: 'RO', ru: 'RU',
    sk: 'SK', sl: 'SI', so: 'SO', sq: 'AL', sv: 'SE', sw: 'TZ',
    ta: 'IN', te: 'IN', th: 'TH', tl: 'PH', tr: 'TR', uk: 'UA',
    ur: 'PK', vi: 'VN', zh: 'CN',
};